name: MATLAB/Octave Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Octave
        run: |
          sudo apt-get update
          sudo apt-get install -y octave

      - name: Run tests
        run: |
          octave-cli --eval "Q1_Q2/runtestQ1"
          octave-cli --eval "Q1_Q2/runtestQ2"
