name: MATLAB/Octave Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Octave
        run: |
          sudo apt-get update
          sudo apt-get install -y octave

      - name: Run tests
        working-directory: ./Q1_Q2  # Set the working directory to Q1_Q2
        run: |
          octave-cli --eval "runtestQ1"
          octave-cli --eval "runtestQ2"

